language: node_js
node_js:
- 12
jobs:
  include:
  - stage: test
    name: lint
    script:
    - npm run lint
  - stage: deploy-prod
    script: skip
    deploy:
      skip_cleanup: true
      provider: script
      script: bash .travis/deploy.sh
      on:
        branch: master

before_deploy:
- openssl aes-256-cbc -K $encrypted_cbcb7b8ba770_key -iv $encrypted_cbcb7b8ba770_iv
  -in travis.enc -out .travis/travis -d

- openssl aes-256-cbc -K $encrypted_b430f37899e7_key -iv $encrypted_b430f37899e7_iv
  -in Polyteach-bc79d4e94e80.json.enc -out ./src/api/Polyteach-bc79d4e94e80.json -d

